version: "3"

services:
  web:
    build: ./api
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./api:/app
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true

  db:
    image: postgres
    volumes:
      - app_postgres:/var/lib/postgresql/data #Windowsの場合 https://qiita.com/jungissei/items/c58bd1158cd909540b26
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin-pass"
    restart: always

  front:
    build: ./front
    volumes:
      - ./front:/app
      - node_modules:/app/node_modules
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
    command: npm run serve

volumes:
  app_postgres:
    external: true #Windowsの場合追加 https://qiita.com/jungissei/items/c58bd1158cd909540b26
  bundle:
  node_modules:
